application:
  config:
    profile: dev_
    url: 'http://192.168.1.16:9124/parkingFlypassService'
aws:
  accessKey: AKIAU25556XO3L7TL3VQ
  secretKey: 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
  arnentryparkingsns: 'arn:aws:sns:us-east-1:332721419741:dev_parking_flypass'
  arnentryparkingsqs: 'arn:aws:sqs:us-east-1:332721419741:dev_parking_flypass_entry'
info:
  component: parkingFlypassService
server:
  servlet:
    context-path: "/parkingFlypassService"
  port: 9124
spring:
  application:
    name: parkingFlypassService
  profiles:
    active: dev
endpoints:
  enabled: false
